# Generated by Django 4.2.25 on 2025-11-02 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username_encrypted', models.CharField(max_length=256)),
                ('password_encrypted', models.CharField(max_length=256)),
                ('role', models.CharField(choices=[('officer', 'Officer'), ('citizen1', 'Citizen1'), ('citizen2', 'Citizen2')], help_text='User role determines dashboard access', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this user account is active')),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
                'db_table': 'user_profiles',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['role'], name='user_profil_role_fa03e1_idx'), models.Index(fields=['created_at'], name='user_profil_created_26443b_idx'), models.Index(fields=['is_active'], name='user_profil_is_acti_44246c_idx')],
            },
        ),
    ]
